name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build the container
              run: docker build -t copsboot -f Dockerfile.dev .
            - name: Run the default test
              run: docker run -e CI=true copsboot


